### ISSUE TITLE
Dont receive any compiler warnings when adding the plugin

### ISSUE THREAD

**Issue by joakimtall** [BraisGabin/detekt-compiler-rules#34]
This might very well be a user error, I have included the plugin like this:

```kotlin
package ...

import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.getByType

internal fun Project.configureDetekt() {
    val libs = extensions.getByType<VersionCatalogsExtension>().named("libs")

    dependencies {
        add("detektPlugins", libs.findLibrary("detekt.formatting").get())
        add("detektPlugins", libs.findLibrary("detekt.compiler.wrapper").get())
    }

    extensions.configure<DetektExtension> {
        config = project.rootProject.files("tools/detekt/detekt.yml")
    }
}
```

Version catalog is 
`detekt-compiler-wrapper = { group = "com.braisgabin.detekt", name = "kotlin-compiler-wrapper", version = "0.0.4" }`

And configured like this in detekt.yml

```yml
compiler:
  active: true # not sure if this is needed, just trial and erroring
  CompilerInfo:
    active: false
    ignoreDiagnostic: []
  CompilerWarning:
    active: true
    ignoreDiagnostic:
      - 'OPT_IN_IS_NOT_ENABLED'
```

Building normally produces a bunch of warnings, like 
`w: /Users/...ApiService.kt: (23, 49): Unnecessary non-null assertion (!!) on a non-null receiver of type String`

But running detekt goes very fast, and reports nothing.

```
./gradlew detekt
...
BUILD SUCCESSFUL in 1s
23 actionable tasks: 1 executed, 22 up-to-date
```

I have also added the formatting plugin to detekt which works, and I have tried to keep the configuration identical.
